services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  shortlink:
    build: .
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable
      LISTEN_ADDR: ':8080'